# Generated by Django 4.2.2 on 2023-06-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
